version: '3.9'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: dampsystem
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dampsys
      MYSQL_PASSWORD: dampsys
    ports: ["3306:3306"]
    volumes: [dbdata:/var/lib/mysql]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  mailpit:
    image: axllent/mailpit:latest
    ports: ["8025:8025","1025:1025"]
  minio:
    image: minio/minio:latest
    command: server /data --console-address ':9001'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000","9001:9001"]
    volumes: [miniodata:/data]
  meilisearch:
    image: getmeili/meilisearch:v1.7
    environment:
      MEILI_NO_ANALYTICS: 'true'
    ports: ["7700:7700"]
  nginx:
    image: nginx:alpine
    volumes:
      - ../backend/public:/var/www/html/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on: [mysql, redis]
volumes:
  dbdata: { }
  miniodata: { }
